const digitalProducts = [
    {
        id: 1,
        title: "Ultimate Passive Income Guide 2026",
        category: "Digital",
        price: 19.99,
        image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Best Seller"
    },
    {
        id: 2,
        title: "Crypto Trading Bot V2 (Source Code)",
        category: "Digital",
        price: 49.99,
        image: "https://images.unsplash.com/photo-1611974765270-ca12586343bb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Popular"
    },
    {
        id: 3,
        title: "Neon Cyberpunk Asset Pack",
        category: "Digital",
        price: 14.99,
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "New"
    },
    {
        id: 4,
        title: "SaaS Starter Kit (Next.js + Tailwind)",
        category: "Digital",
        price: 29.99,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Hot"
    },
    {
        id: 5,
        title: "AI Prompt Engineering Masterclass",
        category: "Digital",
        price: 24.99,
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Trending"
    }
];

const affiliateProducts = [
    {
        "id": 6528,
        "title": "Exclusive: Five Guys Coupon: Buy Any Burger, Get One Free B1G1 Free (Order Online or via Mobile App, Valid thru 3/12/26)",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19286550-five-guys-coupon-buy-any-burger-get-one-free-b1g1-free-order-online-or-via-mobile-app-valid-thru-3-12-26?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2161,
        "title": "Epic: 9-ct Duracell 2032 Lithium Battery $9.40 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19280565-sns-9-39-9-count-duracell-cr2032-3v-lithium-coin-batteries-at-amazon-1-04-each?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5385,
        "title": "Exclusive: Wareon Universal Socket w/ Drill Adapter (7-19mm) $3.60 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19286124-ac-3-59-universal-socket-w-drill-adapter-7-19mm-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9854,
        "title": "Premium: Hamourd Rechargeable Remote Control Robot Toy w/ LED Eyes (blue) $11.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19279194-hamourd-rechargeable-remote-control-emo-robot-toy-w-led-eyes-11-49-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3522,
        "title": "Insane: 5-Quart Winco Stainless Steel Mixing Bowl $5.25 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19286085-5-quart-winco-stainless-steel-mixing-bowl-5-26-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6824,
        "title": "Premium: adidas Men's Essentials Fleece Hoodie (Black/White) $13 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.ebay.com/itm/157736237784?mkcid=1&mkrid=711-53200-19255-0&campid=4tima",
        "badge": "NEW"
    },
    {
        "id": 7905,
        "title": "Exclusive: 2-pk Dewalt Toughseries Construction Jack $119 + $6.49 Shipping",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19286112-acme-dewalt-toughseries-construction-jack-2-pack-bundle-119?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7053,
        "title": "Exclusive: 32-Piece Wiha GoBox Standard Bit Set with Mini Ratchet (74984) $23 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19285233-22-98-32-piece-wiha-gobox-standard-bit-set-with-mini-ratchet-74984-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5150,
        "title": "Premium: 16-Pack DeWALT ToughCase Bi-metal Wood/Metal Reciprocating Saw Blade Set $19 w/ Subscription + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19284903-16-pack-dewalt-toughcase-bi-metal-tpi-wood-metal-cutting-demolition-reciprocating-saw-blade-18-98-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7422,
        "title": "Viral: Slickdeals Daily Draw Giveaway \u2013 Enter Now for a Chance to Win! (See Official Rules) ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/18822175-slickdeals-daily-draw-giveaway-enter-now-for-a-chance-to-win-see-official-rules?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4138,
        "title": "Premium: 41mm Google Pixel Watch 3 Wi-Fi (Black): Open Box $119, New $170 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.bestbuy.com/product/g...J39TC87CX4?ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8840,
        "title": "Epic: 12-Pk 12-oz Celsius Sugar Free Sparkling Energy Drink (Galaxy Vibe) $15.70 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19273542-12-pack-12-oz-celsius-sugar-free-sparkling-energy-drink-galaxy-vibe-15-67-w-s-s-free-shipping-w-prime-or-on-orders-over-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4234,
        "title": "Unbeatable: Transformers 7-Movie Collection (Blu-Ray) $29.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19284822-transformers-7-movie-collection-blu-ray-29-49-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2081,
        "title": "Exclusive: Thermomaven Bristle Free Grill Brush w/ 3 Brush Heads $15 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19273866-14-99-thermomaven-grill-brush-bristle-free-brush-w-3-replacement-heads-red-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6476,
        "title": "Insane: Milwaukee M18 Brushless Super SAWZALL Reciprocating Saw w/ 8.0 Ah Battery $239 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.homedepot.com/p/Milwa.../331594109?ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8869,
        "title": "Viral: Razer BlackShark V2 X Wired Gaming Headset $30 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19282644-29-99-razer-blackshark-v2-x-wired-gaming-headset-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8590,
        "title": "Exclusive: Prime Members: 2-Pack 5000mAH Cordless Rechargeable Table Lamps (Black) $13.40 + Free S/H",
        "category": "Home",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19285377-prime-ac-13-39-2-pack-5000mah-cordless-rechargeable-table-lamps-black-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2106,
        "title": "Epic: $100 Uber eGift Card $85, $50 Golden Corral Gift Card $40 & More",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19286070-40-50-golden-corral-gift-card-more-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1196,
        "title": "Insane: Superman: The Movie (1978, 4K Ultra HD + Blu-ray) $15 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.walmart.com/ip/Superm...om=/search?ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9980,
        "title": "Unbeatable: The North Face Women\u2019s Reaxion 2.0 Hooded Full-Zip Jacket (2 colors) $34 + Free S/H",
        "category": "Beauty",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19264324-the-north-face-women-s-reaxion-2-0-hooded-full-zip-jacket-space-dark-heather-33-98-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8943,
        "title": "Unbeatable: 14 Cu. Ft. Insignia Garage-Ready Chest Freezer $350 + Free Pickup",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.bestbuy.com/product/i...J2FPJKY9X5?ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1597,
        "title": "Viral: Mattel Uno Splash Waterproof Card Game $6.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19284126-mattel-uno-splash-waterproof-card-game-w-take-along-clip-6-49-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8003,
        "title": "Viral: Select Accts: 101-Oz Pompeian Smooth Extra Virgin Olive Oil (First Cold Pressed) $20.80 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19266817-sns-ac-20-77-101-oz-pompeian-smooth-extra-virgin-olive-oil-first-cold-pressed-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2858,
        "title": "Premium: 18V RIGID Dual Function Cordless Inflator (Tool Only) $68.90 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19285314-dotd-rigid-18v-dual-function-cordless-inflator-tool-only-with-valve-adaptor-needle-2-nozzles-and-12v-power-cord-69?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4188,
        "title": "Exclusive: 10\" Metabo HPT 15-Amp Single Bevel Compound Corded Miter Saw $94 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19285038-ac-94-10-metabo-hpt-15-amp-single-bevel-compound-corded-miter-saw-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5049,
        "title": "Epic: Anker Hot Deals: Up to 40% off  + ree shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773073492-anker-portable-power-station-toyp.png?h=87&w=125",
        "link": "https://www.dealnews.com/Anker-Hot-Deals-Up-to-40-off-ree-shipping/21814964.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8471,
        "title": "Insane: Villear 16-Channel OTC Hearing Aids for $66 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773061483-615czdvo2rl-ac_sl1500.jpg?h=121&w=125",
        "link": "https://www.dealnews.com/Villear-16-Channel-OTC-Hearing-Aids-for-66-free-shipping/21814904.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9581,
        "title": "Must-Have: Best Buy Top TV Deals  for Under $500 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763733355-samsung-qled-tv-front-view-zirp.avif?h=83&w=125",
        "link": "https://www.dealnews.com/Best-Buy-Top-TV-Deals-for-Under-500-free-shipping/21814870.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6774,
        "title": "Unbeatable: Refurb Samsung Galaxy Watch 4 Classic 42mm Smart Watch for $56 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773056606-samsung-galaxy-watch-4-classic-2qtz.webp?h=125&w=78",
        "link": "https://www.dealnews.com/Refurb-Samsung-Galaxy-Watch-4-Classic-42-mm-Smart-Watch-for-56-free-shipping/21814863.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9760,
        "title": "Premium: Refurb Unlocked Google Pixel 8 Pro 256GB Phone for $338 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773055546-black-google-smartphone-slmv.webp?h=125&w=101",
        "link": "https://www.dealnews.com/Refurb-Unlocked-Google-Pixel-8-Pro-256-GB-Phone-for-338-free-shipping/21814858.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3352,
        "title": "Viral: Apple AirPods 4 for $99 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1725973075-apple-airpods-charging-case-gwye.jpeg?h=125&w=118",
        "link": "https://www.dealnews.com/products/Apple/Apple-Air-Pods-4/481781.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1096,
        "title": "Premium: Bosch 18V CORE18V Lithium-Ion 4Ah Advanced Power Battery  for $49 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773050032-bosch-core18v-power-tool-battery-ptxu.jpeg?h=73&w=125",
        "link": "https://www.dealnews.com/Bosch-18-V-CORE18-V-Lithium-Ion-4-Ah-Advanced-Power-Battery-for-49-free-shipping/21814835.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4939,
        "title": "Insane: Tech Finds at Woot for From $12 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773041798-sunrise-simulation-alarm-clock-wp2v.jpeg?h=125&w=95",
        "link": "https://www.dealnews.com/Tech-Finds-at-Woot-for-From-12-free-shipping-w-Prime/21814799.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8093,
        "title": "Exclusive: Apple Watch Series 9 GPS + Cellular Smart Watch for From $230 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773040966-dark-blue-apple-smartwatch-navy-band-idp8.jpeg?h=125&w=111",
        "link": "https://www.dealnews.com/Apple-Watch-Series-9-GPS-Cellular-Smart-Watch-for-From-230-free-shipping-w-Prime/21814798.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3470,
        "title": "Premium:  Samsung Galaxy A17 5G 128GB Android Smartphone for Metro by T-Mobile: Free w/ $40 per month Period plan + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772785824-screenshot-2026-03-06-at-08-30-13.png?h=125&w=102",
        "link": "https://www.dealnews.com/Samsung-Galaxy-A17-5-G-128-GB-Android-Smartphone-for-Metro-by-T-Mobile-Free-w-40-per-month-Period-plan-free-shipping/21814796.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9061,
        "title": "Must-Have: TCL Q65 Series 55Q651G 4K QLED UHD Smart TV for $250 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1723486570-dn-image-7857534.jpg?h=125&w=125",
        "link": "https://www.dealnews.com/products/TCL/TCL-Q65-Series-55-Q651-G-4-K-QLED-UHD-Smart-TV/473404.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6363,
        "title": "Unbeatable: JLab Talk USB Microphone for $23 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772981174-black-usb-microphone-front-view-nnxk.jpeg?h=125&w=92",
        "link": "https://www.dealnews.com/JLab-Talk-USB-Microphone-for-23-free-shipping-w-Prime/21814768.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2714,
        "title": "Exclusive: Certified Refurb Eco-Worthy 48V 50Ah LiFePO4 Battery for $320 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772968693-eco-worthy-lifepo4-battery-dxwi.webp?h=67&w=125",
        "link": "https://www.dealnews.com/Certified-Refurb-Eco-Worthy-48-V-50-Ah-Li-Fe-PO4-Battery-for-320-free-shipping/21814755.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2552,
        "title": "Exclusive: Refurb Unlocked Samsung Galaxy Z Fold 4 256GB Android Smart Phone for $327 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1705627066-dn-image-7721682.jpg?h=125&w=94",
        "link": "https://www.dealnews.com/products/Samsung/Unlocked-Samsung-Galaxy-Z-Fold-4-256-GB-Android-Smart-Phone/433944.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3799,
        "title": "Insane: Anker Prime 26,250mAh 300W Powerbank for $125 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772956787-anker-power-bank-usb-ports-djmi.jpeg?h=125&w=55",
        "link": "https://www.dealnews.com/Anker-Prime-26-250-m-Ah-300-W-Powerbank-for-125-free-shipping/21814749.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7492,
        "title": "Unbeatable: Refurb Unlocked Apple iPhone 14 Pro 256GB Phone for $386 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1738425628-apple-iphone-front-back-cawo.jpeg?h=125&w=102",
        "link": "https://www.dealnews.com/products/Apple/Apple-iPhone-14-Pro-256-GB-Phone/486784.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8961,
        "title": "Epic: Refurb Samsung Galaxy Z Flip5 256GB Android Phone for $250 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1757152617-samsung-galaxy-z-flip5-graphite-hero.avif?h=125&w=97",
        "link": "https://www.dealnews.com/products/Samsung/Samsung-Galaxy-Z-Flip5-256-GB-Android-Phone/493580.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6150,
        "title": "Unbeatable: eBay March Promo Code Deals: Extra 20% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1701878759-dn-image-6701341.png?h=50&w=125",
        "link": "https://www.dealnews.com/eBay-March-Promo-Code-Deals-Extra-20-off-free-shipping/21814709.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3965,
        "title": "Must-Have: Game Day TV Deals at Woot: Up to 52% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772877966-screenshot-2026-03-07-at-10-05-55.png?h=76&w=125",
        "link": "https://www.dealnews.com/Game-Day-TV-Deals-at-Woot-Up-to-52-off-free-shipping-w-Prime/21814706.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1298,
        "title": "Epic: JBL Tour Pro 2 True Wireless Noise Cancelling Earbuds: 137.47  + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772182117-black-jbl-wireless-earbuds-wvdn.webp?h=125&w=125",
        "link": "https://www.dealnews.com/products/JBL/JBL-Tour-Pro-2-True-Wireless-Noise-Cancelling-Earbuds/497809.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8173,
        "title": "Unbeatable: Certified Refurb HP OmniBook X Ryzen 7 2-in-1 14\" Touch Laptop for $600 + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773053723-hp-laptop-front-angled-68oh.webp?h=80&w=125",
        "link": "https://www.dealnews.com/products/HP/HP-Omni-Book-X-Ryzen-7-2-in-1-14-Touch-Laptop/497891.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3051,
        "title": "Epic: Certified Refurb Acer Swift Go 14 Ultra 7 14\" Touch Laptop w/ 1TB SSD for $372 + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1762525809-screenshot_2025-11-07_at_14-29-47-removebg-preview.png?h=94&w=125",
        "link": "https://www.dealnews.com/products/Acer/Acer-Swift-Go-14-Core-Ultra-7-155-H-14-Touch-Laptop-w-1-TB-SSD/495627.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5195,
        "title": "Insane: Dell Laptop Deals: Up to $1,250 off + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772827875-apple-macbook-air-laptop-kvfp.png?h=99&w=125",
        "link": "https://www.dealnews.com/Dell-Laptop-Deals-Up-to-1-250-off-free-shipping/21814673.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7334,
        "title": "Insane: Acer Aspire 14 Core Ultra 7 14\" Laptop for $529 + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1770910466-2026-02-12_10-34-12.png?h=94&w=125",
        "link": "https://www.dealnews.com/products/Acer/Acer-Aspire-14-Core-Ultra-7-14-Laptop/497644.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7802,
        "title": "Must-Have: Dell Clearance Deals: Up to 55% off + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772739511-microsoft-surface-laptop-front-view-ifb1.png?h=84&w=125",
        "link": "https://www.dealnews.com/Dell-Clearance-Deals-Up-to-55-off-free-shipping/21814367.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    }
];

const allProducts = [...digitalProducts, ...affiliateProducts];