const digitalProducts = [
    {
        id: 1,
        title: "Ultimate Passive Income Guide 2026",
        category: "Digital",
        price: 19.99,
        image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Best Seller"
    },
    {
        id: 2,
        title: "Crypto Trading Bot V2 (Source Code)",
        category: "Digital",
        price: 49.99,
        image: "https://images.unsplash.com/photo-1611974765270-ca12586343bb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Popular"
    },
    {
        id: 3,
        title: "Neon Cyberpunk Asset Pack",
        category: "Digital",
        price: 14.99,
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "New"
    },
    {
        id: 4,
        title: "SaaS Starter Kit (Next.js + Tailwind)",
        category: "Digital",
        price: 29.99,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Hot"
    },
    {
        id: 5,
        title: "AI Prompt Engineering Masterclass",
        category: "Digital",
        price: 24.99,
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Trending"
    }
];

const affiliateProducts = [
    {
        "id": 1586,
        "title": "Viral: Prime Members: 4-Pk 1-kg OVERTURE PETG 1.75mm 3D Printer Filament (2 Colors) $30.70 w/ S&S + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.amazon.com/dp/B0DPQK5FCV?tag=bigterry20036-20",
        "badge": "NEW"
    },
    {
        "id": 2892,
        "title": "Viral: 5-Qt Castrol GTX Full Synthetic Motor Oil (5W-30) $19.35 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19344159-sns-19-35-castrol-gtx-full-synthetic-5w-30-motor-oil-5-quarts-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3296,
        "title": "Must-Have: 8-Pk 3.75-Oz Dove Men+Care 3-in-1 Bar Soap (Deep Clean) $9.65 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.amazon.com/Moisturizing-Effectively-Washes-Bacteria-Nourishes/dp/B002TSA90W/ref=ast_sto_?tag=bigterry20036-20",
        "badge": "NEW"
    },
    {
        "id": 6768,
        "title": "Must-Have: 12-Oz Amazon Grocery 62% Cocoa Dark Chocolate Chunks $2.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342815-2-50-12oz-amazon-grocery-62-cocoa-dark-chocolate-chunks-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8265,
        "title": "Epic: $50 Applebee's Gift Card $40 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19344093-40-50-applebee-s-gift-card-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7683,
        "title": "Must-Have: Wolfbox DF60 3-Speed 110K RPM Electric Compressed Air Duster $26.55 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19331751-wolfbox-df60-electric-compressed-air-duster-3-speed-26-53-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9040,
        "title": "Epic: 2-Pk Bosch 18V 4Ah Li-ion Batteries w/ Charger + Select Bonus Tool $179 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19332309-free-tool-bosch-18-volt-2-pack-lithium-ion-4-ah-4-ah-battery-kit-gxs18v-11n25?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4484,
        "title": "Epic: 12-Pk 16oz Cellucor C4 Zero Sugar Pre Workout Energy Drink (Popsicle Cherry) $14.60 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19343445-sns-14-57-12-pack-16-oz-cellucor-c4-performance-energy-drink-x-popsicle-cherry-at-amazon-1-21-each?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2135,
        "title": "Unbeatable: Perlegear Full Motion TV Wall Mount for 42-90\" TVs (Holds up to 132-lbs) $31.90 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19323450-perlegear-full-motion-tv-wall-mount-for-42-90-tvs-holds-up-to-132-lbs-31-90-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5230,
        "title": "Unbeatable: LISEN 5000mAh Wireless Qi2 15W Ultra Slim MagSafe Power Bank w/ 22.5W USB-C $17 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19320285-lisen-5000mah-qi2-wireless-15w-ultra-slim-magsafe-power-bank-w-22-5w-usb-c-1-6-usb-c-to-usb-c-cable-ice-gray-16-99?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4396,
        "title": "Epic: 8-Pk 12-Oz Bubly Sparkling Water (Raspberry) $3.20 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342032-8-pack-12-ounce-bubly-sparkling-water-raspberry-3-21-w-s-s-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3552,
        "title": "Must-Have: 3-Pc Fiskars Lopper, Hedge Shear & Pruner Garden Tree & Shrub Care Tool Set $24.50 + Free Pickup",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19338393-3-piece-fiskars-rust-resistant-steel-tree-shrub-care-set-24-49-free-store-pickup-at-target-or-fs-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4775,
        "title": "Premium: 100-Pack 0.5-Oz INABA Churu Cat Treats (Chicken Variety) $33.50 w/ S&S + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19343190-sns-33-48-100-pack-0-5-oz-inaba-churu-cat-treats-chicken-variety-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6190,
        "title": "Must-Have: 26-Oz Turtle Wax Hybrid Solutions Ceramic Wet Wax $8.80 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342332-8-80-26-oz-turtle-wax-hybrid-solutions-ceramic-wet-wax-53410-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3236,
        "title": "Must-Have: 16GB Amazon Kindle Colorsoft eReader (Black) $170 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19332396-169-99-16gb-amazon-kindle-colorsoft-ereader-black-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9776,
        "title": "Premium: Slickdeals Daily Draw Giveaway \u2013 Enter Now for a Chance to Win! (See Official Rules) ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/18822175-slickdeals-daily-draw-giveaway-enter-now-for-a-chance-to-win-see-official-rules?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3453,
        "title": "Must-Have: Maui Jim Polarized Sunglasses (Various Styles/Colors) from $109 + Free Shipping",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19253737-maui-jim-polarized-sunglasses-various-styles-colors-from-109-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9033,
        "title": "Unbeatable: 1.01-Oz Medicube Zero Exosome Shot 2000 PPM Spicule Facial Serum $11.30 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19343319-1-01-oz-medicube-zero-exosome-shot-2-000-ppm-spicule-facial-serum-11-30-w-s-s-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9049,
        "title": "Unbeatable: $100 Nintendo eShop Gift Card (Email Delivery) $85 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342449-100-nintendo-eshop-egift-card-email-delivery-85-via-newegg?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6816,
        "title": "Unbeatable: AMD Ryzen 9 9900X 12-Core/24-Thread Unlocked Desktop Processor $315 + Free S&H",
        "category": "Home",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342086-314-99-amd-ryzen-9-9900x-12-core-24-thread-unlocked-desktop-processor-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3639,
        "title": "Viral: ASUS TUF Gaming B850M-E mATX Motherboard + 1TB Team Group NV5000 M.2 SSD $170 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19341372-asus-tuf-gaming-b850m-e-wifi-amd-b850-matx-motherboard-1tb-team-group-ssd-170-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7017,
        "title": "Viral: 7L Frienhund Timed / Programmable Automatic Cat Feeder w/ 2x Bowls $21 + Free Shipping",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19287270-7l-frienhund-timed-programmable-automatic-cat-feeder-21-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5740,
        "title": "Must-Have: Elden Ring (PS5) $15.20 + Free S/H w/ Amazon Prime",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19341801-15-19-elden-ring-ps5-at-woot?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1025,
        "title": "Unbeatable: Wahl Color Pro Cordless Rechargeable Hair Clipper & Trimmer $24.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19342236-24-49-wahl-color-pro-cordless-rechargeable-hair-clipper-trimmer-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8566,
        "title": "Epic: Columbia Men's Steens Mountain Vest (Black) $13.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19343367-columbia-men-s-steens-mountain-vest-black-size-s-6x-13-48-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5086,
        "title": "Viral: Apple AirPods Big Spring Sale Deals: Up to 22% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763646022-apple-airpods-pro-wireless-earbuds-wgtv.jpeg?h=78&w=125",
        "link": "https://www.dealnews.com/Apple-Air-Pods-Big-Spring-Sale-Deals-Up-to-22-off-free-shipping-w-Prime/21818270.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5213,
        "title": "Insane: Xtra Muse 4K Pocket Camera with Gimbal for $379.00 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774446895-61xqmubmabl-ac_sl1500.jpg?h=125&w=39",
        "link": "https://www.dealnews.com/Xtra-Muse-4-K-Pocket-Camera-with-Gimbal-for-379-00-free-shipping/21818252.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6766,
        "title": "Premium: SwitchBot AI Art Frame 13.3'' Wireless E-Ink Display for $270 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774448475-8157kcpgbsl-ac_sl1500.jpg?h=125&w=116",
        "link": "https://www.dealnews.com/Switch-Bot-AI-Art-Frame-13-3-Wireless-E-Ink-Display-for-270-free-shipping/21818246.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2300,
        "title": "Premium: SmallRig 35\" Quick Release Softbox for $68 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1751955869-61dvv0zmehl-ac_sl1500.jpg?h=125&w=125",
        "link": "https://www.dealnews.com/Small-Rig-35-Quick-Release-Softbox-for-68-free-shipping/21818233.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1999,
        "title": "Exclusive: Viture 120Hz Luma Pro XR Glasses for $359.10 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774447678-61ovgfldnml-ac_sl1500.jpg?h=90&w=125",
        "link": "https://www.dealnews.com/Viture-120-Hz-Luma-Pro-XR-Glasses-for-359-10-free-shipping/21818218.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6553,
        "title": "Premium: Apple AirPods 4 for $100 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1725973075-apple-airpods-charging-case-gwye.jpeg?h=125&w=118",
        "link": "https://www.dealnews.com/products/Apple/Apple-Air-Pods-4/481781.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6456,
        "title": "Exclusive: JLab Big Spring Sale Deals at Amazon: Up to 50% off + Extra 10% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774447458-blue-jlab-wireless-earbuds-q4p0.jpeg?h=125&w=114",
        "link": "https://www.dealnews.com/JLab-Big-Spring-Sale-Deals-at-Amazon-Up-to-50-off-Extra-10-off-free-shipping/21818208.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7344,
        "title": "Epic: Ostation 2 Smart 3-in-1 Battery Charger for $72 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774443263-71sgaxnmvdl-ac_sl1500.jpg?h=125&w=78",
        "link": "https://www.dealnews.com/Ostation-2-Smart-3-in-1-Battery-Charger-for-72-free-shipping/21818190.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8628,
        "title": "Premium: Baofeng 10W Two-Way Radio for $14 + free shipping w/ first order",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774442606-baofeng-bf-1909-two-way-radio-igta.png?h=125&w=67",
        "link": "https://www.dealnews.com/Baofeng-10-W-Two-Way-Radio-for-14-free-shipping-w-first-order/21818184.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8072,
        "title": "Must-Have: Vestaboard Mechanical Smart Messaging Display for $3,499 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773223409-black-vestaboard-message-board-qf8u.webp?h=125&w=125",
        "link": "https://www.dealnews.com/products/Vestaboard/Vestaboard-Mechanical-Smart-Messaging-Display/497916.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1992,
        "title": "Premium: Smallrig V Mount Battery Plate Kit for $152 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774441500-61r3lsulv6l-ac_sl1500.jpg?h=125&w=117",
        "link": "https://www.dealnews.com/Smallrig-V-Mount-Battery-Plate-Kit-for-152-free-shipping/21818181.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9486,
        "title": "Insane: Apple Watch Big Spring Sale Deals at Amazon: Up to 57% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774439074-dark-gray-apple-smartwatch-blue-band-lalx.jpeg?h=125&w=107",
        "link": "https://www.dealnews.com/Apple-Watch-Big-Spring-Sale-Deals-at-Amazon-Up-to-57-off-free-shipping-w-Prime/21818166.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3081,
        "title": "Exclusive: Tech & Gaming Big Spring Sale Deals at Amazon: Up to 62% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1760280475-lenovo-idea-tab-with-pen-and-case-9rve.jpeg?h=95&w=125",
        "link": "https://www.dealnews.com/Tech-Gaming-Big-Spring-Sale-Deals-at-Amazon-Up-to-62-off-free-shipping-w-Prime/21818163.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2427,
        "title": "Premium: Nothing Ear (a) Noise Cancelling Wireless Earbuds for $59 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1765377442-nothing-wireless-earbuds-top-view-lgxv.jpeg?h=109&w=125",
        "link": "https://www.dealnews.com/products/Nothing-Ear-a-Noise-Cancelling-Wireless-Earbuds/498056.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5703,
        "title": "Exclusive: Amazon Devices Big Spring Sale Deals: Up to 69% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1750849370-blink-smart-home-security-cameras-awrs.jpeg?h=120&w=125",
        "link": "https://www.dealnews.com/Amazon-Devices-Big-Spring-Sale-Deals-Up-to-69-off-free-shipping-w-Prime/21818161.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5691,
        "title": "Insane: Walmart Electronics Spring Savings Sale: Up to 85% off + Free shipping w/ $35",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774435315-apple-airpods-pro-charging-case-7hwe.webp?h=125&w=124",
        "link": "https://www.dealnews.com/Walmart-Electronics-Spring-Savings-Sale-Up-to-85-off-Free-shipping-w-35/21818150.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4587,
        "title": "Premium: Samsung Big Spring Sale Deals at Amazon: Up to 50% off + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1770843263-tablet.jpg?h=88&w=125",
        "link": "https://www.dealnews.com/Samsung-Big-Spring-Sale-Deals-at-Amazon-Up-to-50-off-free-shipping-w-Prime/21818134.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2568,
        "title": "Epic: Amazon Fire TV Stick HD with Alexa for $17 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1761939704-amazon-fire-tv-stick-hd-2ohb.jpeg?h=92&w=125",
        "link": "https://www.dealnews.com/products/Amazon/Amazon-Fire-TV-Stick-HD-with-Alexa/484818.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8717,
        "title": "Unbeatable:  2nd-Gen. Amazon Kindle Scribe 16GB 10.2\" eBook Reader (2024) for $250 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1729092237-amazon-kindle-scribe-e-reader-stylus-oihb.jpeg?h=109&w=125",
        "link": "https://www.dealnews.com/products/Amazon/2-nd-Gen-Amazon-Kindle-Scribe-16-GB-10-2-eBook-Reader-2024/488366.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1740,
        "title": "Must-Have: Samsung Galaxy A17 5G 128GB Mint Mobile Android Phone for $20 + a year of Unlimited for $15/month + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774340718-black-samsung-smartphone-front-back-mjyn.png?h=125&w=103",
        "link": "https://www.dealnews.com/Samsung-Galaxy-A17-5-G-128-GB-Mint-Mobile-Android-Phone-for-20-a-year-of-Unlimited-for-15-month-free-shipping/21817808.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3602,
        "title": "Viral: Apple AirTag 4-Pack for $60 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1725040547-dn-image-7861651.jpg?h=68&w=125",
        "link": "https://www.dealnews.com/products/Apple/Apple-Air-Tag-4-Pack/220199.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3696,
        "title": "Epic: Pioneer PN70-R851-26U 70\" 4K HDR LED UHD Smart Roku TV for $300 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1772118267-roku-smart-tv-front-view-h4up.avif?h=125&w=125",
        "link": "https://www.dealnews.com/products/Pioneer/Pioneer-PN70-R851-26-U-70-4-K-HDR-LED-UHD-Smart-Roku-TV/497801.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7652,
        "title": "Exclusive: Samsung Galaxy Watch8 Classic 46mm Bluetooth Smartwatch (2025) for $220 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763045724-huawei-smartwatch-black-band-gxem.jpeg?h=125&w=120",
        "link": "https://www.dealnews.com/products/Samsung/Samsung-Galaxy-Watch8-Classic-46-mm-Bluetooth-Smartwatch-2025/495778.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7565,
        "title": "Premium: Maxell Wireless Stereo Casette Player for $80.30 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774371152-maxell-stereo-cassette-player-pwqr.jpeg?h=125&w=122",
        "link": "https://www.dealnews.com/products/Maxell/Maxell-Wireless-Stereo-Casette-Player/498049.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4226,
        "title": "Epic: SGIN 15.6'' Windows 11 16GB RAM 1024GB SSD Laptop  for $260 + free shipping",
        "category": "Tech",
        "source": "DealNews Home",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773915197-71zqkdqhk1l-ac_sl1500.jpg?h=83&w=125",
        "link": "https://www.dealnews.com/SGIN-15-6-Windows-11-16-GB-RAM-1024-GB-SSD-Laptop-for-260-free-shipping/21816992.html?iref=rss-c49&ref=money_maker_2026",
        "badge": "NEW"
    }
];

const allProducts = [...digitalProducts, ...affiliateProducts];