const digitalProducts = [
    {
        id: 1,
        title: "Ultimate Passive Income Guide 2026",
        category: "Digital",
        price: 19.99,
        image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Best Seller"
    },
    {
        id: 2,
        title: "Crypto Trading Bot V2 (Source Code)",
        category: "Digital",
        price: 49.99,
        image: "https://images.unsplash.com/photo-1611974765270-ca12586343bb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Popular"
    },
    {
        id: 3,
        title: "Neon Cyberpunk Asset Pack",
        category: "Digital",
        price: 14.99,
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "New"
    },
    {
        id: 4,
        title: "SaaS Starter Kit (Next.js + Tailwind)",
        category: "Digital",
        price: 29.99,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Hot"
    },
    {
        id: 5,
        title: "AI Prompt Engineering Masterclass",
        category: "Digital",
        price: 24.99,
        image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
        link: "https://paypal.me/lilterry200369",
        badge: "Trending"
    }
];

const affiliateProducts = [
    {
        "id": 8092,
        "title": "Must-Have: 10-Pack 1kg GEEETECH 1.75mm 3D Printer Filament: PETG White or Black, PLA Black $58.45 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19310643-10-pack-1kg-geeetech-1-75mm-3d-printer-filament-petg-white-or-black-pla-black-58-45-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9574,
        "title": "Epic: 60-Ct 12mg Sports Research Triple Strength Astaxanthin $13.45 w/ S&S",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19322112-sns-ac-13-47-60-count-sports-research-triple-strength-astaxanthin-12mg-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4716,
        "title": "Must-Have: CINCOM Hand Massager w/ Heat & Compression (Various Colors) $24 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19327077-cincom-hand-massager-w-heat-compression-various-colors-24-55-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5314,
        "title": "Epic: Select Accounts: AMD Ryzen 5 7600X 6-Core/12-Thread Unlocked Desktop Processor $159.20 + Free S/H",
        "category": "Home",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334631-ac-ymmv-159-20-amd-ryzen-5-7600x-6-core-12-thread-unlocked-desktop-processor-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4786,
        "title": "Premium: adidas Men's Run 60s 2.0 Shoes (Victory Crimson) $19.20 & More + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334949-adidas-men-run-60s-2-0-shoes-victory-crimson-cloud-white-core-black-19-2?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3408,
        "title": "Insane: Pelsee P1 Pro 4K Front & 1080p Rear Dash Cam w/ STARVIS 2 Sensor $50 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19326642-pelsee-p1-pro-4k-front-1080p-rear-dash-cam-w-starvis-2-sensor-49-99-free-shipping?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2973,
        "title": "Premium: 2-Pk Houoisheck Hat Organizers for Baseball Caps (Black) $5 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19320495-2-pack-houoisheck-hat-organizer-for-baseball-caps-black-4-99-free-shipping-w-prime-or-on-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9947,
        "title": "Must-Have: Pudolla Men's Lightweight Jogger Sweatpants $10 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19321938-pudolla-men-s-lightweight-jogger-sweatpants-10?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3613,
        "title": "Premium: Amazfit Active 2 Sport 44mm Smartwatch w/ Black or Red Silicone Strap $80 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19331406-79-99-amazfit-active-2-sport-44mm-amoled-smartwatch-w-black-or-red-silicone-strap-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1972,
        "title": "Epic: VTech Bluey Ring Ring Phone Toy $7.70 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334484-vtech-bluey-ring-ring-phone-7-69-free-shipping-w-prime-or-on-orders-over-35?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1141,
        "title": "Premium: 60\" Ohniyou Ceiling Fan w/ Aluminum Blades, Light & App/Remote $80 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19313115-60-ohniyou-ceiling-fan-w-aluminum-blades-light-app-remote-80-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4731,
        "title": "Epic: Dearfoams Cozy Comfort Men's Jersey Slide Slippers (Black) from $4.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334628-4-50-to-4-72-dearfoams-cozy-comfort-men-s-jersey-slide-slippers-black-in-many-sizes?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3528,
        "title": "Insane: $50 GAP Gift Card (Email Delivery) $37.50 ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334661-gap-50-gift-card-email-delivery-37-50-banana-republic-athleta-babygap-gap-old-navy-newegg?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1023,
        "title": "Viral: Select Accounts: 27.5\" ESKUTE M200 21-Speed 48V Electric Mountain Bike $295.75 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19322835-select-users-eskute-m200-mountain-ebike-21-speed-27-5-wheels-1200w-peak-28mph-48v-10-4ah-batt-302-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3070,
        "title": "Exclusive: Pok\u00e9mon: The Movies 1-3 Collection (Blu-ray) $12; Pokemon Series (DVD, various) from $11 & More",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19329177-11-99-pok-mon-the-movies-1-3-collection-blu-ray-more-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8935,
        "title": "Premium: WOLFBOX X3 PRO 1440P Front & Rear Dash Cam $120 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19302183-wolfbox-x3-pro-1440p-front-rear-starvis-2-imx675-wifi-6-dash-cam-120-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7789,
        "title": "Exclusive: 4-Pk Apple AirTag Bluetooth Tracking Devices (1st Gen) $60 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334451-59-99-4-pk-apple-airtag-bluetooth-tracking-devices-1st-gen-free-s-h-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7238,
        "title": "Exclusive: DeWALT 20V MAX XR Brushless 3/8\" & 1/2\" Sealed Head Ratchet (Tool Only) $189 + Free S/H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19333869-189-dewalt-20v-max-xr-cordless-ratchet-3-8-and-1-2-sealed-head-ratchet-bare-tool-only-dcf510b-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7414,
        "title": "Epic: Ridgid 18V Brushless 4-Mode 1/2\" Impact Wrench Kit w/ 2x 4Ah Batteries & Charger $179 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19333830-ridgid-18v-brushless-cordless-4-mode-1-2-in-high-torque-impact-wrench-kit-with-2-4-0-ah-lithium-ion-batteries-and-charger-179-at-homedepot?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8774,
        "title": "Unbeatable: Samsung EPP & EDU: 49\" Odyssey G91F 5120x1440p 144Hz VA 1000R Curved Monitor $580 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19302420-samsung-epp-edu-49-odyssey-g91f-5120x1440p-144hz-va-1000r-curved-monitor-600-free-s-h?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4139,
        "title": "Must-Have: 30-Lb Hill's Science Diet Sensitive Stomach & Skin Dry Dog Food $44.10 w/ S&S + Free S&H",
        "category": "Beauty",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334382-sns-ac-44-13-30-pound-hill-s-science-diet-sensitive-stomach-skin-dry-dog-food-chicken-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7693,
        "title": "Must-Have: Slickdeals Daily Draw Giveaway \u2013 Enter Now for a Chance to Win! (See Official Rules) ",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/18822175-slickdeals-daily-draw-giveaway-enter-now-for-a-chance-to-win-see-official-rules?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2142,
        "title": "Exclusive: Google Fi: 50% Off Plans for 12 Months w/ New Line & BYOD: Unlimited Essentials $17.50/mo for 1 line & More (New Customers Only)",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19299600-google-fi-phone-lines-for-50-of-12-month-45?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2609,
        "title": "Insane: 613-Pc LEGO Ideas: Licensed Disney Pixar Luxo Jr. $56 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1350&q=80",
        "link": "https://slickdeals.net/f/19334502-55-99-613-piece-lego-ideas-licensed-disney-pixar-luxo-jr-21357-2025-at-amazon?utm_source=rss&utm_content=fp&utm_medium=RSS2&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9955,
        "title": "Viral: 2-Pk Tracfone Motorola Moto G Power 5G Phone (2024) + 1-Yr 1500Min/Txt/1.5GB $90 + Free S&H",
        "category": "Tech",
        "source": "Slickdeals",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1350&q=80",
        "link": "https://www.ebay.com/itm/287191137918?mkcid=1&mkrid=711-53200-19255-0&campid=4tima",
        "badge": "NEW"
    },
    {
        "id": 4065,
        "title": "Unbeatable: Cosmo Kids' Smartwatches: 15% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774281719-black-cosmo-smartwatch-angled-view-dkil.webp?h=125&w=125",
        "link": "https://www.dealnews.com/Cosmo-Kids-Smartwatches-15-off-free-shipping/21817676.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2110,
        "title": "Unbeatable: Monster S620 60W Portable Bluetooth Speaker for $50 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774273315-816p6y5eg2l-ac_sl1500.jpg?h=66&w=125",
        "link": "https://www.dealnews.com/Monster-S620-60-W-Portable-Bluetooth-Speaker-for-50-free-shipping/21817660.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6069,
        "title": "Must-Have: Apple AirTag 4-Pack for $60 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1725040547-dn-image-7861651.jpg?h=68&w=125",
        "link": "https://www.dealnews.com/products/Apple/Apple-Air-Tag-4-Pack/220199.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5874,
        "title": "Exclusive: Fullmosa Leather Band for Apple Watch 2-Pack for $10 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774276676-71satarv2cl-ac_sl1500.jpg?h=94&w=125",
        "link": "https://www.dealnews.com/Fullmosa-Leather-Band-for-Apple-Watch-2-Pack-for-10-free-shipping-w-Prime/21817649.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3418,
        "title": "Insane: Luckdog 4K BIN-910 Wireless HDMI Transmitter and Receiver for $64 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763158144-71cpsx3e7vl-ac_sl1500.jpg?h=125&w=124",
        "link": "https://www.dealnews.com/Luckdog-4-K-BIN-910-Wireless-HDMI-Transmitter-and-Receiver-for-64-free-shipping/21817623.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1788,
        "title": "Must-Have: Aukey Spark Mega 140W 27,600mAh Power Bank for $50 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774273904-aukey-27600mah-power-bank-zl44.webp?h=125&w=125",
        "link": "https://www.dealnews.com/Aukey-Spark-Mega-140-W-27-600-m-Ah-Power-Bank-for-50-free-shipping/21817618.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2825,
        "title": "Viral: SmallRig x Potato Jet Tribex SE Hydraulic Camera Tripod for $320 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763571090-617r7kb-y8l-ac_sl1500.jpg?h=125&w=82",
        "link": "https://www.dealnews.com/Small-Rig-x-Potato-Jet-Tribex-SE-Hydraulic-Camera-Tripod-for-320-free-shipping/21817613.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9936,
        "title": "Epic: Smallrig 73'' Aluminum Video Tripod for $74 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1768194704-61x82kvkrul-ac_sl1500.jpg?h=125&w=118",
        "link": "https://www.dealnews.com/Smallrig-73-Aluminum-Video-Tripod-for-74-free-shipping/21817605.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7626,
        "title": "Viral: Meifigno Magnetic Car Phone Holder for $9 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1763381403-71-wi8xfayl-ac_sl1500.jpg?h=125&w=98",
        "link": "https://www.dealnews.com/Meifigno-Magnetic-Car-Phone-Holder-for-9-free-shipping-w-Prime/21817591.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 5745,
        "title": "Premium: Vestaboard Mechanical Smart Messaging Display for $3,499 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773223409-black-vestaboard-message-board-qf8u.webp?h=125&w=125",
        "link": "https://www.dealnews.com/products/Vestaboard/Vestaboard-Mechanical-Smart-Messaging-Display/497916.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8124,
        "title": "Insane: SmallRig 110\" Photography Air-Cushioned Aluminum Light Stand / Tripod for $55.20 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1764102418-61oqywwdykl-ac_sl1500.jpg?h=125&w=119",
        "link": "https://www.dealnews.com/Small-Rig-110-Photography-Air-Cushioned-Aluminum-Light-Stand-Tripod-for-55-20-free-shipping/21817589.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2113,
        "title": "Unbeatable: Certified Refurb Viture One XR/AR Glasses for $100 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774269979-black-sunglasses-blue-lenses-angled-3atd.webp?h=103&w=125",
        "link": "https://www.dealnews.com/Certified-Refurb-Viture-One-XR-AR-Glasses-for-100-free-shipping/21817584.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6555,
        "title": "Premium: Mini 1080p Sports Camera for $9 + free shipping w/ first order",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774267932-black-dash-cam-screen-led-xgto.avif?h=125&w=125",
        "link": "https://www.dealnews.com/Mini-1080-p-Sports-Camera-for-9-free-shipping-w-first-order/21817575.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 8322,
        "title": "Premium: Refurb Apple Watch Ultra 2 GPS + Cellular 49mm Titanium Smart Watch for $397 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774263786-apple-watch-ultra-dark-band-d0zb.webp?h=125&w=125",
        "link": "https://www.dealnews.com/products/Apple/Apple-Watch-Ultra-2-GPS-Cellular-49-mm-Titanium-Smart-Watch/497063.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7264,
        "title": "Viral: Unlocked Samsung Galaxy Z Flip7 FE 256GB Phone  for $600 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1760525133-black-samsung-foldable-smartphone-1r0y.png?h=125&w=105",
        "link": "https://www.dealnews.com/products/Samsung/Unlocked-Samsung-Galaxy-Z-Flip7-FE-256-GB-Phone/494949.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2474,
        "title": "Must-Have: Best Buy Speakers Top-Seed Savings: Up to 65% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774258360-black-copper-subwoofer-front-view-ahgw.avif?h=125&w=122",
        "link": "https://www.dealnews.com/Best-Buy-Speakers-Top-Seed-Savings-Up-to-65-off-free-shipping/21817518.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 4708,
        "title": "Unbeatable: Best Buy  Sound Bar Top-Seed Savings: Up to 30% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774257481-samsung-home-audio-system-soundbar-speakers-yye0.avif?h=69&w=125",
        "link": "https://www.dealnews.com/Best-Buy-Sound-Bar-Top-Seed-Savings-Up-to-30-off-free-shipping/21817514.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 9822,
        "title": "Unbeatable: NANK Clip Bluetooth 5.4 Open Ear Earbuds for $24 + free shipping w/ Prime",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774001724-61xbzvsl0el-ac_sl1500.jpg?h=83&w=125",
        "link": "https://www.dealnews.com/NANK-Clip-Bluetooth-5-4-Open-Ear-Earbuds-for-24-free-shipping-w-Prime/21817513.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 1179,
        "title": "Exclusive: Best Buy TV Top-Seed Savings for Under $500 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1764576624-insignia-qled-quantum-dot-led-tv-pguv.avif?h=125&w=125",
        "link": "https://www.dealnews.com/Best-Buy-TV-Top-Seed-Savings-for-Under-500-free-shipping/21817512.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3962,
        "title": "Must-Have: Samsung Galaxy S26 256GB Android Smartphone w/ Mint Mobile 12-Month Plan for $500 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1773332813-samsung-smartphone-front-back-2wgf.avif?h=125&w=104",
        "link": "https://www.dealnews.com/products/Samsung/Unlocked-Samsung-Galaxy-S26-256-GB-Android-Smartphone/497943.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6011,
        "title": "Unbeatable: 3-in-1 Magnetic Wireless Charger for Apple Devices for $16 w/ Prime + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1769078372-71jmyin-9l-ac_sl1500.jpg?h=122&w=125",
        "link": "https://www.dealnews.com/3-in-1-Magnetic-Wireless-Charger-for-Apple-Devices-for-16-w-Prime-free-shipping/21817511.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 7285,
        "title": "Epic:  LG 55\" Class or Larger TV Deals at Best Buy : Up to $1,500 off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774256243-uhd-ai-television-front-view-o4ea.avif?h=78&w=125",
        "link": "https://www.dealnews.com/LG-55-Class-or-Larger-TV-Deals-at-Best-Buy-Up-to-1-500-off-free-shipping/21817510.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 3825,
        "title": "Unbeatable: Unlocked Motorola razr 256GB Phone (2025) for $462 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774254942-motorola-razr-flip-smartphone-svda.jpeg?h=125&w=104",
        "link": "https://www.dealnews.com/Unlocked-Motorola-razr-256-GB-Phone-2025-for-462-free-shipping/21817505.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 2775,
        "title": "Insane: Best Buy Top-Seed Savings: Up to 65% off + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1688045127-dn-image-7243106.png?h=125&w=125",
        "link": "https://www.dealnews.com/Best-Buy-Top-Seed-Savings-Up-to-65-off-free-shipping/21817504.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    },
    {
        "id": 6206,
        "title": "Premium: Glarry 20W Electric Guitar Amplifier for $39 + free shipping",
        "category": "Tech",
        "source": "DealNews Tech",
        "price": "Check Site",
        "originalPrice": "---",
        "image": "https://www.datocms-assets.com/64599/1774218723-black-glarry-ga20-guitar-amplifier-qpjf.avif?h=125&w=125",
        "link": "https://www.dealnews.com/products/Glarry-20-W-Electric-Guitar-Amplifier/498032.html?iref=rss-c142&ref=money_maker_2026",
        "badge": "NEW"
    }
];

const allProducts = [...digitalProducts, ...affiliateProducts];